/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const GameScore = IDL.Record({
  'streak' : IDL.Nat,
  'dailyScoreTimestamp' : Time,
  'scoreTimestamp' : Time,
  'perksEarned' : IDL.Vec(IDL.Text),
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyLeaderboard' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'unlockPerk' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const GameScore = IDL.Record({
    'streak' : IDL.Nat,
    'dailyScoreTimestamp' : Time,
    'scoreTimestamp' : Time,
    'perksEarned' : IDL.Vec(IDL.Text),
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyLeaderboard' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
    'unlockPerk' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };